### ISSUE TITLE
ModelUploadOp from "Vertex AI Pipelines: model upload using google-cloud-pipeline-components"  does not work

### ISSUE THREAD

**Issue by stevenzhang-support** [GoogleCloudPlatform/vertex-ai-samples#349] opened 2022-03-02 00:52 UTC
## Expected Behavior
Code example  from "Vertex AI Pipelines: model train, upload, and deploy using google-cloud-pipeline-components" [1] should work as intended.

## Actual Behavior
Code example below from "Vertex AI Pipelines: model train, upload, and deploy using google-cloud-pipeline-components" [1] had issue and does not work

```
from google_cloud_pipeline_components import aiplatform as gcc_aip
    from google.cloud import aiplatform
    aiplatform.init(project=project, location=region)

    # THIS IS THE METHOD THAT DOESN'T APPEAR TO WORK
    model_upload_op = gcc_aip.ModelUploadOp(
            project=project,
            location=region,
            display_name=model_display_name,
            artifact_uri=model.uri,
            serving_container_image_uri=serving_container_image_uri
            )
```
On the other hand, the method below worked:
```
 # THIS METHOD DOES WORK
    # aiplatform.Model.upload(
    #     display_name=model_display_name,
    #     artifact_uri=model.uri,
    #     serving_container_image_uri=serving_container_image_uri,
    # )
```

I'm currently using Vertex AI Pipelines to train a model and upload to Vertex AI. Currently in the pipeline, I'm attempting to use the ModelUploadOp class to upload a custom model to Vertex AI models. The logs show the job is succeeding, but the model never actually gets uploaded.

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

Version: 
- Pipeline SDK (Kubeflow Pipelines/TFX) Version: kfp
- Pipelines Version: kfp==1.8.11
- Platform: Google Cloud Vertex AI 

[1]: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/pipelines/google_cloud_pipeline_components_model_train_upload_deploy.ipynb

**Comment by andrewferlitsch** [comment] 2022-03-02 20:58
There was a recent breaking change. Will update notebook accordingly.

**Comment by andrewferlitsch** [comment] 2022-03-04 01:50
Notebook has been updated, tested and merged.

**Comment by galz10** [comment] 2022-03-04 05:22
@andrewferlitsch can we close this issue since the notebook is merged ?

**Comment by andrewferlitsch** [comment] 2022-03-04 05:24
yes, I will close it. I thought I had.

**Closed by andrewferlitsch** 2022-03-04 05:24 UTC
Labels: type: bug

**Comment by natetsang** [comment] 2022-03-07 16:28
Hi all,
I saw this thread and the updated notebook - thanks for fixing it. 

I can't help but think that using `artifact_uri=WORKING_DIR` in the Importer Node seems misaligned with Kubeflow's focus on Artifacts and Artifact management. Is it possible to set `artifact_uri` to the Artifact location without hardcoding `WORKING_DIR`?

```
import_unmanaged_model_task = importer_node.importer(
        artifact_uri=WORKING_DIR,        <--- Can we set this without hardcoding WORKING_DIR?
        artifact_class=artifact_types.UnmanagedContainerModel,
        metadata={
            "containerSpec": {
                "imageUri": "us-docker.pkg.dev/cloud-aiplatform/prediction/tf2-cpu.2-3:latest",
            },
        },
    )
```

To make things simple, let's say that instead of putting the training code in CustomTrainingJobOp, you define a custom function (below). In this case wouldn't it be more Kubeflow-ish to replace save the file to `Output[Model].path` instead of hard coding `WORKING_DIR` , like the following? 

```
def train_model(dataset: Input[Dataset],  model: Output[Model]):
      ...

       # then save model
       # model.save(WORKING_DIR)   <---- This is the way outlined in the notebook
       model.save(model.path)         <--- This seems more aligned with KFP than above
```

Then, when you wanted to upload the model, you would again replace `WORKING_DIR` with the location of the Artifact set by Kubeflow.

```
@kfp.dsl.pipeline(name="train-endpoint-deploy" + TIMESTAMP)
def pipeline(
       # enter pipeline params here
):
        ...

        # train model
        train_model_op = train_model(...)

        import_unmanaged_model_task = importer_node.importer(
                artifact_uri=train_model_op.outputs["model"].uri,         <---- USING ARTIFACT LOCATION
                artifact_class=artifact_types.UnmanagedContainerModel,
                metadata={
                     "containerSpec": {
                      "imageUri": serving_container_image_uri,
                 },
               },
           )
```
But unfortunately you can't actually do this because you get an error: "AttributeError: 'PipelinParam' object has no attribute uri'". To avoid this error, you could also nest the Importer Node into a custom Component that has Input[Model] as one of the parameters. Then you could set `artifact_uri=model.uri`. 

```
def custom_importer(trained_model: Input[Model], vertex_model: Output[Model]):
     import_unmanaged_model_task = importer_node.importer(
                artifact_uri=trained_model.uri,         <---- USING ARTIFACT LOCATION
                artifact_class=artifact_types.UnmanagedContainerModel,
                metadata={
                     "containerSpec": {
                      "imageUri": serving_container_image_uri,
                 },
               },
           )
```
Unfortunately, you can't do this as you get "TypeError: There are no registered serializers for type "google.UnmanagedContainerModel"."

**Comment by Ark-kun** [comment] 2022-08-19 01:30
@natetsang If you want an easy way to upload models to Vertex Model Registry, you can use my components: https://github.com/Ark-kun/pipeline_components/tree/KFPv2_hell/components/google-cloud/Vertex_AI/Models 
Example usage: https://github.com/Ark-kun/pipeline_components/blob/05b2f255f8ccd7d8588f8143a76536bf83c2c7c7/samples/Google_Cloud_Vertex_AI/Train_tabular_regression_model_using_TensorFlow_and_import_to_Vertex_AI/pipeline.py#L51

```Python
upload_Tensorflow_model_to_Google_Cloud_Vertex_AI_op = components.load_component_from_url("https://raw.githubusercontent.com/Ark-kun/pipeline_components/719783ef44c04348ea23e247a93021d91cfe602d/components/google-cloud/Vertex_AI/Models/Upload_Tensorflow_model/component.yaml")

...
    vertex_model_name = upload_Tensorflow_model_to_Google_Cloud_Vertex_AI_op(
        model=model,
    ).outputs["model_name"]
```
Where `model` is a `TensorflowSavedModel` artifact that was produced by `model.save(model_path)`.

Please open an issue in my repo if you have any issues or feature requests for the components I've linked.
